sudo: false

language: python

cache:
  - pip

before_install:
  - pip install coveralls>=1.1

install:
  - pip install tox

matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27
    - python: 3.6
      env: TOX_ENV=py36

env:
  - TESTCASE=tests/test_handler.py
  - TESTCASE=tests/tests_middleware.py
  - TESTCASE=tests/tests_placebo.py
  - TESTCASE=tests/tests_async.py
  - TESTCASE=tests/tests.py

after_success:
  coveralls

notifications:
  slack: zappateam:TTJ0mfHunDK0IBweKkEXjGpR
